# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: false
mathjax: false

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# Links
# links:

# Miscellaneous
google_analytics: G-0NB5ZTSTQS
favicon: /favicon.png
twitter:
google_plus:
fb_admins: 
fb_app_id:

disqus_shortname: james-thinking-log